# Google Cloud Platform Configuration
region: us-central1
machine_type: n2-standard-4
database:
  tier: db-custom-4-15360
  engine: postgresql
  storage: 100
ai_platform:
  machine_type: n1-standard-4
monitoring:
  stackdriver_enabled: true
  alerts_enabled: true
security:
  vpc_enabled: true
  encryption_at_rest: true
  ssl_enabled: true
